version: '3'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
          SQL_DATABASE: wpdb
          SQL_USER: ajuliao
          SQL_PASSWORD: 123@Password321
          SQL_ROOT_PASSWORD: 123@Password321
    volumes:
      - mariadb:/var/lib/mysql
    networks:
     - inception
    ports:
     - "3306:3306"
    # restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:42
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
     - wordpress:/var/www/html
    ports:
     - "9000:9000"
    networks:
     - inception
    restart: always
    depends_on:
     - mariadb

  nginx:
    container_name: nginx
    image: nginx:42
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
     - wordpress:/var/www/html
    ports:
     - "443:443"
    networks: 
     - inception
    depends_on:
     - mariadb
     - wordpress

volumes:
  wordpress:
    name: wordpress
    external: true
  mariadb:
    name: mariadb
    external: true
